---
- hosts: mac-dev
  vars:
    casks:
      - google-chrome
      - iterm2
      - dropbox

  tasks:
    - include: ansible-deps.yml

    - name: 'install direnv'
      homebrew:
        name: direnv

    - name: "cask install {{ item.name }}"
      homebrew_cask:
        name: "{{ item }}"
      with_items: "{{ casks }}"

    - include_role:
        name: luan-vim

    - include_role:
        name: git

    - name: copy ~/.bashrc
      copy:
        src: bashrc
        dest: "{{ ansible_env.HOME }}/.bashrc"
        owner: "{{ ansible_env.USER }}"
        mode: 0644
